
version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run:
         command: |
          name: Build Application
  test:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run:
         command: | 
          name: Test Application

 # deploy:
  #  docker:
   #   - image: cimg/base:2022.09
    #steps:
     # - checkout
#      - run:
#          name: Build Application
workflows:
  springapp:
    jobs:
      - build
      - test:
          requires:
            - build
     # - hold:
      #    type: approval
       #   requires:
        #    - build
         #   - test
     # - deploy:
      #    requires:
       #     - hold
