version: 2.1
executors:
  docker-executor:
    docker:
      - image: cimg/python:3.8.4

jobs:
  build_and_deploy:
    executor: docker-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Authenticate with Google Cloud
          command: |
            echo $GOOGLE_SERVICE_KEY | base64 --decode -i > ${HOME}/gcloud-service-key.json
              #cat ${HOME}/gcloud-service-key.json
            #gcloud auth activate-service-account $GOOGLE_SERVICE_KEY --key-file $HOME/gcloud-service-key.json
            gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GOOGLE_PROJECT_ID

      - run:
          name: Build and tag Docker image
          command: |
            docker build -t image1:latest .  
            docker tag image1:latest gcr.io/$GOOGLE_PROJECT_ID/image1:latest

      - run:
          name: Authenticate with Artifact Registry
          command: |
            gcloud auth configure-docker us-central1-docker.pkg.dev

      - run:
          name: Push Docker image to Artifact Registry
          command: |
            docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT_ID/thematic-metric-381904/circle-ci/image1:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
