version: 2.9

jobs:
  build:
    docker:
      - image:
    steps:
      - checkout
      - run:
          name: Build Application
  test:
    docker:
      - image:
    steps:
      - checkout
      - run:
          name: Build Application
  hold:
    docker:
      - image:
    steps:
      - checkout
      - run:
          name: Build Application
  deploy:
    docker:
      - image:
    steps:
      - checkout
      - run:
          name: Build Application        