
version: 2.1
jobs:
  build_and_deploy_job:
    docker:
      - image: hello-world
    steps:
      - checkout
      - cloudrun/init
      - cloudrun/build:
          tag: gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}
      - cloudrun/deploy:
          image: gcr.io/${GOOGLE_PROJECT_ID}/test-${CIRCLE_SHA1}
          platform: managed
          region: us-central1
          service-name: example-service
          unauthenticated: true
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.0

workflows:
  build_and_deploy_to_managed_workflow:
    jobs:
      - build_and_deploy_job
