version: 2.1
executors:
  docker-executor:
    docker:
      - image: circleci/python:3.8
jobs:
  build_and_deploy:
    executor: docker-executor
    steps:
      - checkout
      

      - setup_remote_docker:
          version: 20.10.7


      #- run:
          #name: Authenticate with Google Cloud
          #command: |
            
      - run:
          name: Build and tag Docker image
          command: |
            docker build -t image1:latest .  
            docker tag image1:latest us-central1-docker.pkg.dev/thematic-metric-381904/circle-ci/image1:latest
            
    #  - run:
     #     name: Authenticate with Artifact Registry
      #    command: |
            

      - run:
          name: Push Docker image to Artifact Registry
          command: |
            curl https://sdk.cloud.google.com | bash -s -- --disable-prompts > /dev/null
            export PATH=${HOME}/google-cloud-sdk/bin:${PATH}
            echo $GOOGLE_SERVICE_KEY > ${HOME}/gcloud-service-key.json
              #cat ${HOME}/gcloud-service-key.json
            #gcloud auth activate-service-account $GOOGLE_SERVICE_KEY --key-file $HOME/gcloud-service-key.json
            gcloud auth activate-service-account $GOOGLE_SA_NAME --key-file=${HOME}/gcloud-service-key.json
            gcloud config set project $GOOGLE_PROJECT_ID
            echo Y | gcloud auth configure-docker us-central1-docker.pkg.dev
            docker push us-central1-docker.pkg.dev/thematic-metric-381904/circle-ci/image1:latest
            - cloudrun/init
      - cloudrun/build:
          tag: us-central1-docker.pkg.dev/thematic-metric-381904/circle-ci/test-${CIRCLE_SHA1}
      - cloudrun/deploy:
          image: us-central1-docker.pkg.dev/thematic-metric-381904/circle-ci/test-${CIRCLE_SHA1}
          platform: managed
          region: us-central1
          service-name: example-service1
          unauthenticated: true
orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.0

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_deploy
