apiVersion: apps/v1
kind: Deployment
metadata:
  name: travis-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: spring-app
        image: northamerica-northeast2-docker.pkg.dev/gold-circlet-418404/testreposync/springapp-test:latest
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"

--- 
# A load balancer is type of service which will expose an IP and route the requests to this IP to the internal pods.     
apiVersion: v1
kind: Service
metadata:
  name: travis-spring-app
spec:
  type: LoadBalancer
  selector:
    app: spring
  ports:
  - port: 80
    targetPort: 8080
  


#CLOUD RUN
# apiVersion: serving.knative.dev/v1
# kind: Service
# metadata:
#   name: travis-spring-app
# spec:
#   template:
#     spec:
#       containers:
#       - image: europe-west2-docker.pkg.dev/thematic-metric-381904/travis-test/springapp-test:latest
#         ports:
#         - containerPort: 8080
